on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '35 22 * * *'
jobs:
  build-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install bundler
        run: gem install bundler -v 2.2.33
      - name: Install dependencies
        run: bundle install
      - name: Update README content
        run: ruby scripts/content_builder.rb
        env:
          GOODREADS_API_KEY: ${{ secrets.GOODREADS_API_KEY }}
          GOODREADS_SECRET_KEY: ${{ secrets.GOODREADS_SECRET_KEY }}
          GOODREADS_USER_ID: ${{ secrets.GOODREADS_USER_ID }}
      - name: Commit and push
        run: ./entry.sh
